---
title: "catastro_agricola"
author: "AJ"
date: "22-09-2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(readxl)
library(tidyverse)
library(lubridate)
library(plotly)

```

```{r leer datos, include=FALSE}
#in.rds<-"../output/rds"
in.rds<-"E:/ALBERTO/HEMERA/GITHUB/catastro_agricola/output/rds"

dir(in.rds, pattern ="cultivos_superficie_especie", full.names = T ) %>%
  read_rds()->cultivos_superficie

dir(in.rds, pattern ="cultivos_rendimiento_especie", full.names = T ) %>%
  read_rds()->cultivos_rendimiento

dir(in.rds, pattern ="frutales_superficie", full.names = T ) %>%
  read_rds()->frutales_superficie

dir(in.rds, pattern ="frutales_rendimiento", full.names = T ) %>%
  read_rds()->frutales_rendimiento
```

# Indice  {.tabset}

## Cultivos  {.tabset}

### Region

#### Superficie
```{r, echo=FALSE, message = FALSE}
#superficie
cultivos_superficie %>%
    filter(especie %in% c("trigo", "maíz")) %>%
    filter(año>year("1999-01-01")) %>%
    ggplot(aes(año,superficie_ha, fill=especie)) +
      geom_col(position = "dodge")+
      facet_wrap(~nom_region)+
      theme_bw()+
      theme(axis.text.x =   element_text(angle=90),
           legend.position = "bottom")

```

#### Rendimiento 
```{r, echo=FALSE, message = FALSE}
#rendimiento
cultivos_rendimiento %>%
    filter(especie %in% c("trigo", "maíz")) %>%
    filter(año>year("1999-01-01")) %>%
    ggplot(aes(año,rendimiento_ton_ha, fill=especie)) +
      geom_col(position = "dodge")+
      facet_wrap(~nom_region)+
      theme_bw()+
      theme(axis.text.x =   element_text(angle=90),
            legend.position = "bottom")
```


## Frutales  {.tabset}
### Region 

#### Superficie
```{r, echo=FALSE,message = FALSE}
## Vizualizacion frutales

## regiones
#superficie
frutales_superficie %>%
  group_by(nom_region, año, especie) %>%
  summarise(superficie_ha=sum(superficie_ha, na.rm = T)) %>%
  filter(especie %in% c("kiwi", "cerezo")) %>%
  filter(año>year("1999-01-01")) %>%
  ggplot(aes(año,superficie_ha, fill=especie)) +
    geom_col(position = "dodge")+
    facet_wrap(~nom_region)+
    theme_bw()+
    theme(axis.text.x =   element_text(angle=90),
          legend.position = "bottom")

```

#### Rendimiento
```{r}
#rendimiento
frutales_rendimiento %>%
  group_by(nom_region, año, especie) %>%
  summarise(rendimiento_ton_ha=sum(rendimiento_ton_ha, na.rm = T)) %>%
  filter(especie %in% c("kiwi", "cerezo")) %>%
  filter(año>year("1999-01-01")) %>%
  ggplot(aes(año,rendimiento_ton_ha, fill=especie)) +
    geom_col(position = "dodge")+
    facet_wrap(~nom_region)+
    theme_bw()+
    theme(axis.text.x =   element_text(angle=90),
          legend.position = "bottom")
```


### Comunas

#### Superficie
```{r, echo=FALSE,message = FALSE}

## comunas
#superficie
frutales_superficie %>%
  filter(nom_region=="o'higgins") %>%
  filter(especie %in% c("kiwi", "cerezo")) %>%
  filter(año>year("1999-01-01")) %>%
  ggplot(aes(año,superficie_ha, fill=especie)) +
    geom_col(position = "dodge")+
    facet_wrap(~comuna)+
    theme_bw()+
    theme(axis.text.x =   element_text(angle=90),
          legend.position = "bottom")

```

#### Rendimiento
```{r,  echo=FALSE,message = FALSE}

#rendimiento
frutales_rendimiento %>%
  filter(nom_region=="o'higgins") %>%
  filter(especie %in% c("kiwi", "cerezo")) %>%
  filter(año>year("1999-01-01")) %>%
  ggplot(aes(año,rendimiento_ton_ha, fill=especie)) +
    geom_col(position = "dodge")+
    facet_wrap(~comuna)+
    theme_bw()+
    theme(axis.text.x =   element_text(angle=90),
          legend.position = "bottom")
```

